### ISSUE TITLE
Armv7l support

### ISSUE THREAD

**Issue by gasgallo** [XiaoMi/mace#667]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

Is `armv7l` abi still supported? I can find some tutorials for rpi, but it seems that support has been dropped?

**Comment by lu229** [comment]
@gasgallo The `armv7l` abi is not suported, we supoort `armhf`, what  is your device? does it support `armhf`?

**Comment by gasgallo** [comment]
@lu229 my device is https://azure.github.io/Vision-AI-DevKit-Pages/, how can I check if `armhf` is supported?

`uname -a` returns `Linux qcs605-32 4.9.123-perf #1 SMP PREEMPT Fri Feb 7 04:06:59 UTC 2020 armv7l armv7l armv7l GNU/Linux`.

And when I try to convert model and run with `armhf` abi, then I get following error:
```
/tmp/data/mace_run/mace_run_static: relocation error: /tmp/data/mace_run/mace_run_static: symbol _ZTINSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
```

**Comment by lu229** [comment]
@gasgallo I don't know how can check if `armhf` is supported, but in my `raspberrypi` device, `uname -a` returns `Linux raspberrypi 4.14.50-v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l GNU/Linux`, and it support `armhf`, perhaps you can try it.

The error is because the `libstdc++.so.6` in your os is too old, perhaps you can update a new so, for security reasons you can backup the old before you update it.

**Comment by gasgallo** [comment]
@lu229 I've updated the library to `libstdc++.so.6.0.25` and it works with `armhf` target, thank you!
